### ISSUE TITLE
error: The final argument to magicString.overwrite(...) should be an options object

### ISSUE THREAD

**Issue by crooy** [Apercu/butternut-webpack-plugin#7]
In our big webpack build we have this error, sadly due to copyright i cannot give you our source code, i could send you the webpack config if it helps.

```
The final argument to magicString.overwrite(...) should be an options object. See https://github.com/rich-harris/magic-string

/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/IfStatement.js:41
		return this.alternate.getLeftHandSide();
                       ^
TypeError: Cannot read property 'getLeftHandSide' of null
    at Node.getLeftHandSide (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/IfStatement.js:41:24)
    at Node.getLeftHandSide (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/BlockStatement.js:101:24)
    at Node.prepend (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/Node.js:136:27)
    at Node.parenthesize (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/Node.js:131:8)
    at Node.rewriteAsTernaryExpression (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/IfStatement.js:325:55)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/IfStatement.js:236:10)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/BlockStatement.js:226:15)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/shared/FunctionNode.js:108:13)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/ObjectExpression.js:20:13)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/Node.js:121:32)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/CallExpression.js:132:15)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/Node.js:124:12)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/AssignmentExpression.js:56:15)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/VariableDeclaration.js:80:21)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/BlockStatement.js:226:15)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/shared/FunctionNode.js:108:13)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/ParenthesizedExpression.js:100:14)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/Node.js:121:32)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/shared/Array.js:46:15)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/Node.js:121:32)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/types/CallExpression.js:132:15)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/Node.js:124:12)
    at Node.minify (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/BlockStatement.js:226:15)
    at Program (/Users/ronald/Development/withlocals/node_modules/butternut/src/program/Program.js:59:12)
    at squash (/Users/ronald/Development/withlocals/node_modules/butternut/src/index.js:20:9)
    at Compilation.compilation.plugin (/Users/ronald/Development/withlocals/node_modules/butternut-webpack-plugin/dist/index.js:39:57)
    at Compilation.applyPluginsAsyncSeries (/Users/ronald/Development/withlocals/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Users/ronald/Development/withlocals/node_modules/webpack/lib/Compilation.js:640:10)
    at next (/Users/ronald/Development/withlocals/node_modules/webpack/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/Users/ronald/Development/withlocals/node_modules/extract-text-webpack-plugin/dist/index.js:272:11)

```

**Comment by Tokimon** [comment]
Reason should be found with [this issue](https://github.com/Rich-Harris/butternut/issues/172)

**Comment by balthazar** [comment]
Which still seem to be unresolved for now 🙁
